### ISSUE TITLE
Changing secondary types has no effect

### ISSUE THREAD

**Issue by elaverack** [pikalytics/pikalytics-calc#17]
Bug:
Damage calculation doesn't occur properly if the second type of the pokemon is changed.

1. Enter Pikalytics set Abomasnow into both sides of the calculator.
2. Change either pokemon's secondary type to be one that doesn't resist ice.

Expected:
Damage results update to take into account the new typing.

Screenshot
![image](https://user-images.githubusercontent.com/15278208/110193064-d7778980-7dff-11eb-8cd9-e37d14951fcb.png)

Desktop:
 - OS: Windows 10
 - Browser: Chrome

Additional:
Found the wrong code and created a pull request that fixes it.

**Comment by pikalytics** [comment]
Resolved by https://github.com/pikalytics/pikalytics-calc/pull/16

Thank you!
