### ISSUE TITLE
Grapploct doesn't exist in the damage calc sections and Clobbapus has the wrong base stats

### ISSUE THREAD

**Issue by AllyInnes99** [pikalytics/pikalytics-calc#32]
**Describe the bug**
Grapploct cannot be searched for in the damage calc section of the website, and its pre-evolution Clobbapus has the incorrect base stats (it has the stats that Grapploct should have)

**To Reproduce**
1. Go to https://www.pikalytics.com/calc
2. Using the select pokemon dropdown, search for "Grapploct". This yields no results, with the message "No matches found".
3. Using the select pokemon dropdown, search for "Clobbapus". Select Clobbapus and identify that the pokemon has incorrectly listed base stats (https://pokemondb.net/pokedex/clobbopus) 

**Expected behavior**
1. Grapploct should be available to select for damage calcs
2. Clobbapus should have the correct base stats

**Screenshots**

Screenshot of searching for Grapploct
![Screenshot 2021-09-26 151232](https://user-images.githubusercontent.com/33691141/134811559-dbf339d2-49cf-496f-a5b7-5663abb092b6.png)

Screenshot of searching for Clobbapus, and it's base stats
![Screenshot 2021-09-26 151301](https://user-images.githubusercontent.com/33691141/134811564-c2255eeb-2c1d-4ddd-94bd-07f4bfba4896.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 93.0.4577.82

**Comment by Evangelos-Dimos** [comment]
how can I contribute?

**Comment by pikalytics** [comment]
This was previously fixed shortly after this issue was opened. The resolution commit can be found here:

https://github.com/pikalytics/pikalytics-calc/commit/0819725eabb339b613661377bdca50319a7188d7
